import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { NextPageWithLayout } from './page'
import Layout from '@components/layout/Layout'
import { Eth_BG } from '@utils/imageHelper'

const Home: NextPageWithLayout = () => {
  return (
    <div className='flex flex-col w-full h-full justify-center items-center p-48 space-y-16'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h1 className='text-7xl font-black uppercase'>
          Welcome to <a href="#" className='text-[#0070f3]'>this project</a>
      </h1>
      <div className='flex flex-col justify-center items-center rounded-xl pt-16'>
        <Image alt='' src={Eth_BG.image} height={Eth_BG.height/4} width={Eth_BG.width/4} />
      </div>
    </div>
  )
}

Home.getLayout = (page) => {
  return (
    <Layout>{page}</Layout>
  )
}

export default Home


